'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Aktarim_Fis
    Public Property Aktarim_ID As Integer
    Public Property Aktarim_No As Nullable(Of Integer)
    Public Property Aktarim_Tarih As Nullable(Of Date)
    Public Property Aktarim_Türü As String
    Public Property Cikis_Depo_ID As Nullable(Of Integer)
    Public Property Giris_Depo_ID As Nullable(Of Integer)
    Public Property Aktarim_Aciklama As String

    Public Overridable Property Aktarim_Detay As ICollection(Of Aktarim_Detay) = New HashSet(Of Aktarim_Detay)
    Public Overridable Property Depo As Depo
    Public Overridable Property Depo1 As Depo

End Class
