'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Bolum
    Public Property Bolum_ID As Integer
    Public Property Bolum_Adi As String

    Public Overridable Property Fis As ICollection(Of Fis) = New HashSet(Of Fis)

End Class
