'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cari
    Public Property Firma_ID As Integer
    Public Property Firma_Kodu As Nullable(Of Integer)
    Public Property Firma_Adi As String
    Public Property Firma_Adres As String
    Public Property ilce_ID As Nullable(Of Integer)
    Public Property il_ID As Nullable(Of Integer)
    Public Property Vergi_No As Nullable(Of Integer)
    Public Property Vergi_Dairesi As String
    Public Property Firma_Yetkili As String
    Public Property Firma_Tel As String
    Public Property Firma_Cep As String
    Public Property Firma_Fax As String
    Public Property Firma_Web As String
    Public Property Firma_Mail As String
    Public Property Durum As Nullable(Of Boolean)

    Public Overridable Property Cari_Detay As ICollection(Of Cari_Detay) = New HashSet(Of Cari_Detay)
    Public Overridable Property Fatura As ICollection(Of Fatura) = New HashSet(Of Fatura)

End Class
