'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cari_Detay
    Public Property Detay_ID As Integer
    Public Property Firma_ID As Nullable(Of Integer)
    Public Property Borc As Nullable(Of Decimal)
    Public Property Alacak As Nullable(Of Decimal)
    Public Property Bakiye As Nullable(Of Decimal)

    Public Overridable Property Cari As Cari

End Class
