'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Depo
    Public Property Depo_ID As Integer
    Public Property Depo_Kodu As Nullable(Of Integer)
    Public Property Depo_Adi As String
    Public Property Depo_Adres As String
    Public Property ilce_ID As Nullable(Of Integer)
    Public Property il_ID As Nullable(Of Integer)
    Public Property Depo_Yetkili As String
    Public Property Depo_Tel As String
    Public Property Depo_Fax As String
    Public Property Depo_Mail As String
    Public Property Durum As Nullable(Of Boolean)

    Public Overridable Property il As il
    Public Overridable Property ilce As ilce
    Public Overridable Property Fis As ICollection(Of Fis) = New HashSet(Of Fis)
    Public Overridable Property Urun As ICollection(Of Urun) = New HashSet(Of Urun)

End Class
