'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Fatura_Detay
    Public Property Detay_ID As Integer
    Public Property Fatura_ID As Nullable(Of Integer)
    Public Property Urun_ID As Nullable(Of Integer)
    Public Property Miktar As Nullable(Of Integer)
    Public Property Birim As String
    Public Property Fiyat As Nullable(Of Decimal)
    Public Property Tutar As Nullable(Of Decimal)
    Public Property Kdv As Nullable(Of Integer)
    Public Property İndirim As Nullable(Of Integer)

    Public Overridable Property Fatura As Fatura
    Public Overridable Property Urun As Urun

End Class
