'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Fatura
    Public Property Fatura_ID As Integer
    Public Property Fatura_No As Nullable(Of Integer)
    Public Property Fatura_Tarihi As Nullable(Of Date)
    Public Property Fatura_Sevk_Tarihi As Nullable(Of Date)
    Public Property Fatura_Türü As String
    Public Property Depo_ID As Nullable(Of Integer)
    Public Property Firma_ID As Nullable(Of Integer)
    Public Property Fatura_Tutar As Nullable(Of Decimal)
    Public Property Fatura_Aciklama As String

    Public Overridable Property Cari As Cari
    Public Overridable Property Fatura_Detay As ICollection(Of Fatura_Detay) = New HashSet(Of Fatura_Detay)

End Class
