'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Fis_Detay
    Public Property Detay_ID As Integer
    Public Property Fis_ID As Nullable(Of Integer)
    Public Property Urun_ID As Nullable(Of Integer)
    Public Property Miktar As Nullable(Of Integer)
    Public Property Birim_ID As Nullable(Of Integer)
    Public Property Fiyat As Nullable(Of Decimal)
    Public Property Tutar As Nullable(Of Decimal)

    Public Overridable Property Fis As Fis
    Public Overridable Property Urun As Urun

End Class
