'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class il
    Public Property il_ID As Integer
    Public Property il_Plaka As Nullable(Of Short)
    Public Property il_Adi As String

    Public Overridable Property Depo As ICollection(Of Depo) = New HashSet(Of Depo)
    Public Overridable Property ilce As ICollection(Of ilce) = New HashSet(Of ilce)

End Class
