'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ilce
    Public Property ilce_ID As Integer
    Public Property ilce_Adi As String
    Public Property il_ID As Nullable(Of Integer)

    Public Overridable Property Depo As ICollection(Of Depo) = New HashSet(Of Depo)
    Public Overridable Property il As il

End Class
