'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Kullanici
    Public Property Kisi_ID As Integer
    Public Property Kisi_Adi As String
    Public Property Kisi_Soyadi As String
    Public Property Kisi_Tel As String
    Public Property Kisi_Eposta As String
    Public Property KullaniciAdi As String
    Public Property Parola As String
    Public Property Rol_ID As Nullable(Of Integer)

    Public Overridable Property Rol As Rol

End Class
