'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Rol
    Public Property Rol_ID As Integer
    Public Property Rol_Adi As String

    Public Overridable Property Kullanici As ICollection(Of Kullanici) = New HashSet(Of Kullanici)

End Class
