'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Urun
    Public Property Urun_ID As Integer
    Public Property Stok_Kodu As Nullable(Of Integer)
    Public Property Stok_Adi As String
    Public Property Kategori_ID As Nullable(Of Integer)
    Public Property Stok_Barkod As Nullable(Of Integer)
    Public Property Stok_Miktar As Nullable(Of Integer)
    Public Property Birim_ID As Nullable(Of Integer)
    Public Property Stok_TSeviye As Nullable(Of Integer)
    Public Property Depo_ID As Nullable(Of Integer)
    Public Property Stok_AFiyati As Nullable(Of Decimal)
    Public Property Stok_SFiyati As Nullable(Of Decimal)
    Public Property Stok_Kdv As Nullable(Of Integer)
    Public Property Stok_KayitTarihi As Nullable(Of Date)
    Public Property Stok_Foto As String
    Public Property Durum As Nullable(Of Boolean)

    Public Overridable Property Aktarim_Detay As ICollection(Of Aktarim_Detay) = New HashSet(Of Aktarim_Detay)
    Public Overridable Property Birim As Birim
    Public Overridable Property Depo As Depo
    Public Overridable Property Fatura_Detay As ICollection(Of Fatura_Detay) = New HashSet(Of Fatura_Detay)
    Public Overridable Property Fis_Detay As ICollection(Of Fis_Detay) = New HashSet(Of Fis_Detay)
    Public Overridable Property Kategori As Kategori

End Class
